# Generated by Django 3.1.5 on 2021-02-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
