# Generated by Django 3.1.5 on 2021-02-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0003_remove_ninjas_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ninjas',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
